export const MODAL = {
  COMPONENT: [
    'm-auto',
    'rounded-md',
    'bg-gray-medium',
    'border',
    'border-accent',
    'shadow-lg',
    'w-[95%]',
    'max-w-[600px]',
    'm-4',
  ],
  HEADER: {
    CONTAINER: [
      'flex',
      'justify-between',
      'items-center',
      'p-4',
      'gap-4',
      'border-b',
      'border-primary',
    ],
    TITLE: ['text-xl', 'font-semibold', 'text-black'],
  },
  CONTENT: {
    CONTAINER: ['p-4'],
    CHECKOUT_PAGE: {
      CONTAINER: ['flex', 'flex-col', 'items-center', 'gap-5'],
      TITLE: ['text-center', 'text-xl', 'font-bold', 'text-black'],
    },
    ABOUT: {
      CONTAINER: ['flex', 'flex-col', 'p-4'],
      IMAGE: ['w-full', 'h-[500px]', 'object-cover', 'object-bottom', 'rounded-t-lg'],
      NAME: [
        'font-bold',
        'text-[24px]',
        'px-1',
        'bg-accent',
        'text-center',
        'text-white-permanent',
        'rounded-b-xl',
        'py-2',
      ],
      ROLE: [
        'text-[16px]',
        'text-dark',
        'px-1',
        'place-self-start',
        'w-fit',
        'uppercase',
        'min-h-[35px]',
        'mt-2',
      ],
      GITHUB: ['mt-auto', 'pt-4'],
      DESCRIPTION: ['mt-8', 'text-md', 'flex-grow'],
    },
  },
};
