export const ADDRESS = {
  CONTAINER: [
    'flex',
    'flex-col',
    'gap-4',
    'p-3',
    'md:p-4',
    'bg-white',
    'rounded-md',
    'border',
    'border-primary',
  ],
  TITLE: ['text-xl', 'font-semibold', 'text-dark', 'mb-2'],
  CARD: {
    DEFAULT: [
      'p-3',
      'md:p-4',
      'flex',
      'flex-row',
      'gap-8',
      'bg-white',
      'rounded-md',
      'border',
      'border-primary',
    ],
    DEFAULT_TITLE: ['text-sm', 'font-semibold', 'text-accent', 'mb-2'],
    ACTIVE: ['bg-orange-light'],
    BTN_CONTAINER: [
      'flex',
      'flex-col',
      'gap-2',
      'justify-end',
      'justify-start',
      'shrink-0',
      'md:min-w-[200px]',
    ],
    CARD_INFO: ['flex', 'flex-col', 'gap-4', 'flex-grow'],
    ICON: ['w-5', 'h-5'],
    TEXT: ['text-sm', 'md:block', 'hidden'],
  },
  LINE: {
    CONTAINER: ['flex', 'flex-col', 'md:flex-row', 'gap-4', 'text-dark'],
    TITLE: ['font-semibold', 'text-base', 'w-[200px]', 'shrink-0'],
    VALUE: ['text-base', 'break-words', 'break-all'],
  },
};
