export const ADDRESS = {
  CONTAINER: ['border', 'border-accent', 'relative', 'rounded-md', 'px-4', 'pt-14', 'pb-5'],
  TITLE: [
    'absolute',
    '-top-4',
    'left-1/2',
    '-translate-x-1/2',
    'text-nowrap',
    'text-base',
    'md:text-xl',
    'font-bold',
    'text-white',
    'bg-accent',
    'p-1',
    'rounded-md',
  ],
  CARD: {
    DEFAULT: ['rounded-md', 'p-2', 'flex', 'gap-1'],
    DEFAULT_TITLE: [
      'absolute',
      '-top-4.5',
      'left-1/2',
      '-translate-x-1/2',
      'font-bold',
      'bg-primary',
      'pt-1',
      'px-1',
      'rounded-md',
      'text-nowrap',
      'text-sm',
      'md:text-base',
    ],
    ACTIVE: ['bg-primary', 'relative'],
    BTN_CONTAINER: ['flex', 'flex-col', 'gap-2'],
  },
  LINE: {
    CONTAINER: ['flex', 'gap-4', 'text-dark'],
    TITLE: ['font-bold', 'text-sm', 'md:text-base', 'xl:text-xl'],
    VALUE: ['text-sm', 'md:text-base', 'xl:text-xl'],
  },
};
