export const CART_ITEM = {
  CONTAINER: [
    'grid',
    'grid-cols-[150px_1fr]',
    'md:grid-cols-[80px_1fr_100px_150px]',
    'items-center',
    'relative',
    'px-3',
    'py-5',
    'gap-1',
    'md:gap-3',
  ],
  IMAGE: [
    'w-[80px]',
    'h-[80px]',
    'object-contain',
    'm-auto',
    'm-[0px]',
    'cursor-pointer',
    'border',
    'border-transparent',
    'rounded-lg',
    'hover:border-accent',
  ],
  INFO: {
    CONTAINER: [
      'md:pl-5',
      'justify-self-start',
      'flex',
      'flex-col',
      'text-l',
      'font-bold',
      'group',
      'cursor-pointer',
    ],
    NAME: ['text-black', 'group-hover:text-accent-hover', 'transition', 'inline-block', 'pr-7'],
    PRICE: ['text-accent', 'group-hover:text-accent-hover', 'transition', 'inline-block'],
  },
  PRICE: {
    DEFAULT: ['font-bold', 'text-left', 'md:text-right', 'md:pr-5', 'text-black'],
    ACCENT: ['text-accent'],
    OLD: ['text-dark', 'line-through', 'block', 'text-sm', 'font-normal'],
  },
};
