const TAB_BUTTON = [
  'flex',
  'justify-center',
  'xl:justify-start',
  'items-center',
  'gap-2',
  'p-3',
  'font-semibold',
  'transition-colors',
  'text-center',
  'xl:text-left',
  'text-sm',
  'xl:w-full',
  'w-full',
  'rounded-md',
  'border',
  'text-dark',
  'hover:bg-accent-hover',
  'hover:border-accent-hover',
  'cursor-pointer',
];

export const TAB = {
  CONTAINER: [
    'flex',
    'flex-row',
    'xl:flex-col',
    'gap-5',
    'h-fit',
    'overflow-hidden',
    'w-full',
    'justify-between',
    'xl:justify-start',
    'group',
  ],
  BUTTON_STYLE: {
    DEFAULT: [
      ...TAB_BUTTON,
      'bg-white',
      'border-primary',
      'fill-black',
      'text-black',
      'hover:fill-white-permanent',
      'hover:text-white-permanent',
    ],
    ACTIVE: [
      ...TAB_BUTTON,
      'bg-accent',
      'border-accent',
      'fill-white-permanent',
      'text-white-permanent',
    ],
  },
  ICON: ['w-8', 'h-8'],
  NAME: ['hidden', 'md:block'],
};
