const MODAL_SLIDER = {
  SLIDER: [
    'border-none',
    'outline-none',
    'h-screen',
    'relative',
    'aspect-square',
    'inset-5',
    'mx-auto',
    'flex',
    'justify-center',
    'items-center',
    'rounded-lg',
  ],
  FRAME: [
    'absolute',
    'w-full',
    'h-full',
    'bg-no-repeat',
    'bg-contain',
    'bg-center',
    'opacity-0',
    'invisible',
    'transition-opacity',
    'duration-500',
    'ease-in-out',
    'rounded-lg',
  ],
  FRAME_ACTIVE: ['opacity-100', 'visible'],
  CROSS: ['absolute'],
  LEFT_ARROW: [
    'absolute',
    'top-[50%]',
    '-translate-y-[50%]',
    'cursor-pointer',
    'text-2xl',
    'select-none',
    'left-[20px]',
    'hover:bg-accent',
  ],
  RIGHT_ARROW: [
    'absolute',
    'top-[50%]',
    '-translate-y-[50%]',
    'cursor-pointer',
    'text-2xl',
    'select-none',
    'right-[20px]',
    'hover:bg-accent',
  ],
};

export default MODAL_SLIDER;
