const MODAL_SLIDER = {
  SLIDER: [
    'border-none',
    'outline-none',
    'h-[75vh]',
    'relative',
    'aspect-square',
    'inset-5',
    'm-auto',
    'flex',
    'justify-center',
    'items-center',
    'rounded-lg',
    'bg-white',
  ],
  FRAME: [
    'absolute',
    'w-full',
    'h-full',
    'm-2',
    'opacity-0',
    'invisible',
    'transition-opacity',
    'duration-500',
    'ease-in-out',
    'shadow-md',
    'flex',
    'items-center',
    'justify-center',
  ],
  SLIDER_IMAGE: ['max-w-full', 'max-h-full', 'object-contain', 'min-w-[300px]'],
  FRAME_ACTIVE: ['opacity-100', 'visible'],
  CROSS: [
    'absolute',
    'top-4',
    'right-4',
    'flex',
    'justify-center',
    'items-center',
    'text-accent',
    'text-4xl',
    'font-bold',
    'cursor-pointer',
    'hover:text-accent-hover',
    'transition-colors',
    'duration-200',
    'z-10',
    'leading-none',
  ],
  ARROW: [
    'absolute',
    'rounded',
    'p-2',
    'bg-gray/50',
    'flex',
    'justify-center',
    'items-center',
    'text-3xl',
    'font-bold',
    'text-accent',
    'select-none',
    'cursor-pointer',
    'hover:text-accent-hover',
    'transition-colors',
    'duration-200',
    'z-10',
    'leading-none',
  ],
  LEFT_ARROW: ['left-4'],
  RIGHT_ARROW: ['right-4'],
};

export default MODAL_SLIDER;
