const MODAL_SLIDER = {
  SLIDER: [
    'border-none',
    'outline-none',
    'h-[75vh]',
    'relative',
    'aspect-square',
    'inset-5',
    'm-auto',
    'flex',
    'justify-center',
    'items-center',
    'rounded-lg',
    'bg-white',
  ],
  FRAME: [
    'absolute',
    'w-full',
    'h-full',
    'm-2',
    'opacity-0',
    'invisible',
    'transition-opacity',
    'duration-500',
    'ease-in-out',
    'shadow-md',
    'flex',
    'items-center',
    'justify-center',
  ],
  SLIDER_IMAGE: [
    'w-full',
    'max-w-[70%]',
    'md:max-w-[85%]',
    'max-h-full',
    'object-contain',
    'md:min-w-[250px]',
  ],
  FRAME_ACTIVE: ['opacity-100', 'visible'],
  CROSS: [
    'absolute',
    'top-4',
    'right-4',
    'flex',
    'justify-center',
    'items-center',
    'text-4xl',
    'font-bold',
    'cursor-pointer',
    'hover:text-accent-hover',
    'transition-colors',
    'duration-200',
    'z-10',
    'leading-none',
    'hover:text-secondary',
    'text-secondary-light',
  ],
  ARROW: [
    'absolute',
    'rounded',
    'p-2',
    'flex',
    'justify-center',
    'items-center',
    'text-3xl',
    'font-bold',
    'select-none',
    'cursor-pointer',
    'hover:text-secondary',
    'text-secondary-light',
    'transition-colors',
    'duration-200',
    'z-10',
    'leading-none',
  ],
  LEFT_ARROW: ['left-4'],
  RIGHT_ARROW: ['right-4'],
};

export default MODAL_SLIDER;
