import { CHECKBOX_STYLE } from '@/styles/inputs/inputs';

export const FILTERS_STYLES = {
  WRAPPER: ['flex', 'flex-col', 'gap-6', 'relative', 'min-h-[60px]', 'xl:min-h-[150px]'],
  CONTAINER: [
    'hidden',
    'grid',
    'grid-cols-1',
    'sm:grid-cols-2',
    'md:grid-cols-3',
    'gap-6',
    'xl:flex',
    'xl:flex-col',
  ],
  FILTER_CONTAINER: ['flex', 'flex-col', 'gap-2'],
  FILTER_TITLE: ['text-lg', 'font-semibold'],
  OPTIONS_CONTAINER: ['flex', 'flex-col', 'gap-2'],
  OPTION_CONTAINER: ['flex', 'items-center', 'gap-2'],
  CHECKBOX: CHECKBOX_STYLE,
  LABEL: ['text-sm'],
  HIDDEN: ['hidden'],
  DROPDOWN: [
    'max-w-[275px]',
    'bg-white',
    'border',
    'border-black/55',
    'rounded',
    'px-4',
    'py-2',
    'text-dark',
    'text-sm',
    'cursor-pointer',
    'hover:border-black',
    'focus:outline-none',
    'focus:border-black',
    'w-full',
    'sm:w-auto',
  ],
  RANGE_CONTAINER: ['flex', 'items-center', 'gap-2'],
  RANGE_INPUT: [
    'w-20',
    'h-[35px]',
    'px-2',
    'py-1',
    'border',
    'border-black/55',
    'rounded',
    'text-sm',
    'hover:border-black',
    'focus:outline-none',
    'focus:border-black',
    '[appearance:textfield]',
    '[&::-webkit-outer-spin-button]:appearance-none',
    '[&::-webkit-inner-spin-button]:appearance-none',
  ],
  RANGE_LABEL: ['text-sm', 'text-black'],
  SELECTED_FILTERS_CONTAINER: [
    'flex',
    'flex-col',
    'gap-2',
    'p-4',
    'bg-orange-light',
    'rounded',
    'mb-5',
  ],
  FILTER_TAGS: ['flex', 'flex-wrap', 'gap-2'],
  FILTER_ITEM: [
    'flex',
    'items-center',
    'gap-1',
    'px-2',
    'py-1',
    'bg-white',
    'border',
    'border-orange',
    'rounded',
    'text-sm',
  ],
  FILTER_ITEM_VALUE: ['text-black'],
  FILTER_LIST: ['flex', 'flex-col', 'gap-2'],
  FILTER_LIST_TITLE: ['text-sm', 'font-semibold', 'text-dark'],
  FILTERS_CONTAINER: ['flex', 'flex-col', 'gap-4'],
  FILTERS_TITLE: ['text-lg', 'font-semibold', 'mb-2'],
  NO_FILTERS_MESSAGE: ['text-sm', 'text-dark', 'mt-2'],
  EMPTY_FILTERS_CONTAINER: [
    'flex',
    'flex-col',
    'align-start',
    'justify-center',
    'gap-3',
    'items-center',
    'min-h-[100px]',
    'mt-5',
  ],
  EMPTY_FILTERS_IMAGE: ['w-[75px]', 'xl:w-[125x]', 'grow-0'],
  EMPTY_FILTERS_TEXT: ['text-accent', 'text-xl', 'font-semibold', 'text-center'],
};
