export const PRODUCT_LIST_STYLES = {
  CONTAINER: ['w-full', 'flex', 'flex-col', 'gap-6'],
  PRODUCTS_CONTAINER: [
    'w-full',
    'grid',
    'grid-cols-1',
    'sm:grid-cols-2',
    'lg:grid-cols-3',
    'gap-7',
  ],
  CARD: [
    'cursor-pointer',
    'flex',
    'flex-col',
    'bg-white',
    'border',
    'border-primary',
    'rounded-lg',
    'shadow-md',
    'transition-transform',
    'duration-300',
    'ease-in-out',
    'hover:scale-105',
    'hover:bg-primary',
  ],
  IMAGE_CONTAINER: ['w-full', 'h-45', 'flex', 'items-center', 'justify-center'],
  IMAGE: ['max-h-full', 'max-w-full', 'object-contain'],
  CONTENT_CONTAINER: ['px-4', 'py-6', 'flex', 'flex-col', 'flex-grow', 'gap-2'],
  TITLE: ['text-xl', 'font-semibold', 'text-dark'],
  DESCRIPTION: ['text-dark', 'text-sm', 'flex-grow'],
  PRICE_CONTAINER: ['flex', 'items-center', 'gap-4', 'mt-auto', 'pt-5'],
  ORIGINAL_PRICE: ['text-dark', 'line-through', 'text-sm'],
  REGULAR_PRICE: ['text-accent', 'font-semibold', 'text-lg'],
};
