export const PRODUCT_LIST_STYLES = {
  CONTAINER: ['w-full', 'flex', 'flex-col', 'gap-6', 'relative'],
  PRODUCTS_CONTAINER: [
    'w-full',
    'grid',
    'grid-cols-1',
    'sm:grid-cols-2',
    'lg:grid-cols-3',
    'gap-7',
  ],
  CARD: [
    'cursor-pointer',
    'flex',
    'flex-col',
    'bg-white',
    'border',
    'border-primary',
    'rounded-lg',
    'shadow-md',
    'transition-transform',
    'duration-300',
    'ease-in-out',
    'hover:border-orange',
  ],
  IMAGE_CONTAINER: ['w-full', 'h-45', 'flex', 'items-center', 'justify-center', 'relative'],
  IMAGE: ['max-h-full', 'max-w-full', 'object-contain', 'mt-5'],
  CONTENT_CONTAINER: ['px-4', 'py-6', 'flex', 'flex-col', 'flex-grow', 'gap-2'],
  TITLE: ['text-xl', 'font-semibold', 'text-dark'],
  DESCRIPTION: ['text-dark', 'text-sm', 'flex-grow', 'mb-3'],
  PRICE_CONTAINER: [
    'flex',
    'items-center',
    'justify-between',
    'mt-auto',
    'pt-5',
    'border-t',
    'border-primary',
  ],
  PRICE_WRAPPER: ['flex', 'items-center', 'gap-4'],
  ORIGINAL_PRICE: ['text-dark', 'line-through', 'text-sm'],
  REGULAR_PRICE: ['text-accent', 'font-semibold', 'text-lg'],
  PHOTO_COUNTER: ['flex', 'items-center', 'gap-1'],
  CAMERA_ICON: ['w-4', 'h-4', 'fill-black'],
  PHOTO_COUNT: ['text-black', 'text-sm'],
  PROMO_TAG: [
    'absolute',
    'top-2',
    'right-2',
    'bg-accent',
    'text-white-permanent',
    'rounded-lg',
    'px-3',
    'py-1',
    'text-sm',
    'font-semibold',
    'z-10',
  ],
  EMPTY_CATALOG_CONTAINER: [
    'flex',
    'flex-col',
    'items-center',
    'justify-center',
    'gap-6',
    'absolute',
    'inset-0',
    'backdrop-blur-sm',
    'z-10',
    'min-h-[300px]',
  ],
  EMPTY_CATALOG_IMAGE: ['w-[250px]'],
  EMPTY_CATALOG_TEXT: ['text-accent', 'text-xl', 'font-semibold', 'text-center'],
};
