export const SORTING_STYLES = {
  CONTAINER: [
    'w-full',
    'flex',
    'flex-col',
    'sm:flex-row',
    'items-start',
    'sm:items-center',
    'justify-between',
    'gap-4',
    'px-4',
    'py-4',
    'border',
    'border-primary',
    'bg-primary',
    'rounded-lg',
  ],
  PRODUCT_COUNTER: [
    'text-black',
    'text-sm',
    'w-full',
    'text-center',
    'sm:w-auto',
    'sm:text-left',
    'flex-shrink-0',
    'min-w-[150px]',
  ],
  DROPDOWN_CONTAINER: ['flex', 'items-center', 'gap-4', 'w-full', 'sm:w-auto'],
  DROPDOWN: [
    'bg-white',
    'border',
    'border-primary',
    'rounded-lg',
    'px-4',
    'py-2',
    'text-dark',
    'text-sm',
    'cursor-pointer',
    'hover:border-orange',
    'focus:outline-none',
    'focus:border-orange',
    'w-full',
    'sm:w-auto',
  ],
  SEARCH_CONTAINER: ['relative', 'w-full', 'sm:max-w-[350px]', 'flex', 'items-center'],
  SEARCH_INPUT: [
    'bg-white',
    'border',
    'border-primary',
    'rounded-lg',
    'pl-4',
    'pr-14',
    'py-2',
    'text-dark',
    'text-sm',
    'w-full',
    'hover:border-orange',
    'focus:outline-none',
    'focus:border-orange',
  ],
  SEARCH_ICON: ['w-5', 'h-5'],
  SHORT_SEARCH_QUERY: ['absolute', '-bottom-4', 'left-1', 'text-black/80', 'text-[10px]'],
};
