export const SORTING_STYLES = {
  CONTAINER: [
    'w-full',
    'flex',
    'flex-col',
    'sm:flex-row',
    'items-start',
    'sm:items-center',
    'justify-between',
    'gap-4',
    'px-4',
    'border',
    'border-orange-light',
    'rounded-lg',
    'py-4',
  ],
  PRODUCT_COUNTER: ['text-dark', 'text-sm', 'w-full', 'text-center', 'sm:w-auto', 'sm:text-left'],
  DROPDOWN_CONTAINER: ['flex', 'items-center', 'gap-4', 'w-full', 'sm:w-auto'],
  DROPDOWN_LABEL: ['text-dark', 'text-sm', 'hidden', 'sm:block'],
  DROPDOWN: [
    'bg-white',
    'border',
    'border-orange-light',
    'rounded-lg',
    'px-4',
    'py-2',
    'text-dark',
    'text-sm',
    'cursor-pointer',
    'hover:border-red',
    'focus:outline-none',
    'focus:border-red',
    'w-full',
    'sm:w-auto',
  ],
};
