export const SORTING_STYLES = {
  CONTAINER: [
    'w-full',
    'flex',
    'flex-col',
    'sm:flex-row',
    'items-start',
    'sm:items-center',
    'justify-between',
    'gap-4',
    'px-4',
    'border',
    'border-primary',
    'rounded-lg',
    'py-4',
  ],
  PRODUCT_COUNTER: [
    'text-dark',
    'text-sm',
    'w-full',
    'text-center',
    'sm:w-auto',
    'sm:text-left',
    'flex-shrink-0',
  ],
  DROPDOWN_CONTAINER: ['flex', 'items-center', 'gap-4', 'w-full', 'sm:w-auto'],
  DROPDOWN: [
    'bg-white',
    'border',
    'border-primary',
    'rounded-lg',
    'px-4',
    'py-2',
    'text-dark',
    'text-sm',
    'cursor-pointer',
    'hover:border-orange',
    'focus:outline-none',
    'focus:border-orange',
    'w-full',
    'sm:w-auto',
  ],
  SEARCH_CONTAINER: ['relative', 'w-full', 'sm:max-w-[350px]'],
  SEARCH_INPUT: [
    'bg-white',
    'border',
    'border-primary',
    'rounded-lg',
    'pl-4',
    'pr-8',
    'py-2',
    'text-dark',
    'text-sm',
    'w-full',
    'hover:border-orange',
    'focus:outline-none',
    'focus:border-orange',
  ],
  CLEAR_BUTTON: [
    'absolute',
    'right-3',
    'top-1/2',
    '-translate-y-1/2',
    'text-accent',
    'hover:text-accent-hover',
    'cursor-pointer',
    'hidden',
    'text-lg',
    'font-bold',
  ],
};
