export const ABOUT_STYLE = {
  MAIN_CONTAINER: [
    'bg-gray-light',
    'px-3',
    'md:px-4',
    'md:bg-[url(@/assets/images/promo/bg.png)]',
    'md:bg-left-top',
    'bg-size-[80%]',
  ],
  TITLE: ['text-3xl', 'font-semibold', 'text-center', 'text-purple', 'my-6'],
  CONTAINER: ['w-full', 'flex', 'justify-between', 'gap-8', 'my-10', 'mx-4'],
  IMAGE_CONTAINER: [
    'relative',
    'place-self-center',
    'lg:place-self-start',
    'top-4',
    'lg:h-[300px]',
    'lg:max-h-[25%]',
  ],
  PERSONAL_CONTAINER: [
    'flex',
    'flex-col',
    'flex-1',
    'bg-white',
    'border-2',
    'border-solid',
    'border-gray',
    'outline-2',
    'outline-solid',
    'outline-orange',
    'outline-offset-8',
  ],
  ODD_CONTAINER: ['flex', 'flex-col'],
  PHOTO: ['w-[250px]'],
  OLGA_HAT: ['relative', 'hidden', 'lg:block', '-top-116', 'left-30', 'rotate-15', 'w-[225px]'],
  KONSTANTIN_HAT: [
    'relative',
    'hidden',
    'lg:block',
    '-top-114',
    'left-43',
    'rotate-17',
    'w-[185px]',
  ],
  DANIIL_HAT: ['relative', 'hidden', 'lg:block', '-top-123', 'left-16', 'rotate-1', 'w-[250px]'],
  TEXT_CONTAINER: [
    'w-full',
    'p-4',
    // 'shadow-md',
    'rounded-lg',
    'lg:w-2/3',
  ],
  FINALLY_CONTAINER: [
    'max-w-screen-xl',
    'mx-auto',
    'mb-4',
    'p-4',
    'bg-orange',
    'border',
    'border-solid',
    'border-orange',
    'shadow-md',
    'rounded-lg',
  ],
  IMAGE: ['mx-auto'],
  RSSCHOOL_LINK: [
    'max-w-screen-xl',
    'mx-auto',
    'flex',
    'py-2',
    'px-8',
    'relative',
    'top-10',
    'sm:top-12',
    'justify-center',
    'w-fit',
    'bg-orange',
    'rounded-lg',
    'border-accent-hover',
    'border-6',
    'shadow-md',
    'hover:bg-white',
    'hover:border-accent',
  ],
  RSLOGO: ['w-[200px]', 'block'],
  NAME: ['font-bold', 'text-[26px]', 'my-2', 'px-1', 'bg-orange'],
  ROLE: ['font-bold', 'text-[10px]', 'text-dark', 'mb-6', 'w-fit', 'uppercase'],
  DESCRIPTION: ['mb-4'],
  DESCRIPTION_PARAGRAPH: ['mb-2', 'text-black'],
  DESCRIPTION_THANKS: ['font-bold', 'text-accent', 'my-10', 'text-[20px]', 'text-center'],
};
