export const ABOUT_STYLE = {
  MAIN_CONTAINER: [
    'relative',
    'w-full',
    'px-4',
    'pt-5',
    'lg:pt-15',
    'pb-10',
    'flex',
    'flex-col',
    'text-dark',
    'leading-normal',
    'bg-gray-light',
    'flex-grow',
  ],
  TITLE: ['text-3xl', 'font-semibold', 'text-center', 'text-dark', 'mb-12'],
  CONTAINER: [
    'w-full',
    'max-w-[1440px]',
    'mx-auto',
    'grid',
    'grid-cols-1',
    'sm:grid-cols-2',
    'xl:grid-cols-4',
    'gap-6',
  ],
  PERSONAL_CONTAINER: [
    'bg-white',
    'rounded-xl',
    'shadow-md',
    'overflow-hidden',
    'transition-transform',
    'p-6',
    'border',
    'border-primary',
    'flex',
    'flex-col',
    'h-full',
  ],
  ADD_CONTAINER: ['flex', 'flex-col', 'bg-white', 'rounded-lg', 'h-full'],
  ODD_CONTAINER: ['flex', 'flex-col', 'h-full'],
  IMAGE_CONTAINER: ['flex', 'flex-col', 'mb-4'],
  PHOTO: ['w-full', 'h-full', 'object-cover'],
  TEXT_CONTAINER: ['flex', 'flex-col', 'gap-2', 'flex-grow'],
  NAME: [
    'font-bold',
    'text-[20px]',
    'px-1',
    'bg-accent',
    'text-center',
    'text-white-permanent',
    'rounded-b-xl',
    'py-2',
  ],
  ROLE: [
    'text-[12px]',
    'text-dark',
    'px-1',
    'place-self-start',
    'w-fit',
    'uppercase',
    'min-h-[40px]',
  ],
  DESCRIPTION: ['mb-4', 'text-md', 'lg:overflow-hidden', 'hover:overflow-y-auto', 'flex-grow'],
  DESCRIPTION_PARAGRAPH: ['mb-2', 'px-1', 'text-black'],
  DESCRIPTION_THANKS: ['font-bold', 'text-accent', 'text-[18px]', 'text-center'],
  MORE_LINK: [
    'font-bold',
    'italic',
    'block',
    'mt-2',
    'text-secondary',
    'hover:text-accent-hover',
    'cursor-pointer',
  ],
  GIT: ['mt-auto', 'pt-4'],
  FINALLY_CONTAINER: [
    'w-full',
    'max-w-[1440px]',
    'mx-auto',
    'mt-10',
    'p-9',
    'bg-primary',
    'border',
    'border-solid',
    'border-accent',
    'shadow-md',
    'rounded-lg',
    'flex',
    'flex-col',
    'items-center',
  ],
  PARAGRAPH: ['mb-8', 'text-lg', 'text-black', 'last:mb-0'],
  IMAGE: ['mx-auto'],
  RSSCHOOL_LINK: [
    'max-w-screen-xl',
    'mx-auto',
    'flex',
    'py-2',
    'px-8',
    'relative',
    'top-10',
    'sm:top-12',
    'justify-center',
    'w-fit',
    'bg-primary',
    'rounded-lg',
    'border-accent-hover',
    'border-6',
    'shadow-md',
    'hover:bg-white',
    'hover:border-accent',
  ],
  RSLOGO: ['w-[215px]', 'block'],
  TRIBUTE_TEXT: ['text-lg', 'text-center', 'mb-8', 'text-dark'],
  TRIBUTE_CONTAINER: [
    'w-full',
    'max-w-[1440px]',
    'mx-auto',
    'mt-10',
    'p-9',
    'bg-primary',
    'border',
    'border-solid',
    'border-accent',
    'shadow-md',
    'rounded-lg',
    'flex',
    'flex-col',
    'items-center',
  ],
  ADDITIONAL_PARAGRAPHS: ['flex', 'flex-col', 'gap-4', 'w-full', 'mb-8'],
  HIDDEN: ['hidden'],
  VISIBLE: ['block'],
};
