export const ABOUT_STYLE = {
  MAIN_CONTAINER: ['w-full', 'max-w-[1440px]', 'mx-auto', 'px-3', 'md:px-4', 'bg-gray-light'],
  TITLE: ['text-3xl', 'font-semibold', 'text-center', 'text-purple', 'my-6'],

  CONTAINER: [
    'w-full',
    'max-w-[1440px]',
    'justify-center',
    'gap-2',
    'my-10',
    'md:mt-25',
    'flex',
    'flex-wrap',
    'md:justify-around',
  ],
  PERSONAL_CONTAINER: [
    'w-[300px]',
    'p-2',
    'border-2',
    'border-solid',
    'border-primary',
    'flex',
    'bg-white',
    'rounded-lg',
  ],
  ADD_CONTAINER: [
    'flex',
    'flex-col',
    'bg-white',
    'border-2',
    'border-solid',
    'border-gray',
    'rounded-lg',
  ],
  ODD_CONTAINER: ['flex', 'flex-col'],
  IMAGE_CONTAINER: ['h-[300px]', 'relative', 'place-self-center', 'lg:place-self-start', 'mx-auto'],
  PHOTO: [],
  DANIIL_HAT: ['relative', 'hidden', 'lg:block', '-top-78', 'left-10', '-rotate-8', 'w-[180px]'],
  KONSTANTIN_HAT: ['relative', 'hidden', 'lg:block', '-top-85', 'left-27', 'rotate-17'],
  OLGA_HAT: ['relative', 'hidden', 'lg:block', '-top-81', 'left-17', 'rotate-15'],
  TEXT_CONTAINER: [
    'w-full',
    'rounded-lg',
    'grid',
    'grid-cols-1',
    'grid-rows-[50px_50px_180px_30px]',
  ],
  NAME: ['font-bold', 'text-[24px]', 'my-2', 'px-1', 'bg-orange'],
  ROLE: ['font-bold', 'text-[10px]', 'text-dark', 'px-1', 'pb-4', 'mb-6', 'w-fit', 'uppercase'],
  DESCRIPTION: ['mb-4'],
  DESCRIPTION_PARAGRAPH: ['mb-2', 'px-1', 'text-black'],
  DESCRIPTION_THANKS: ['font-bold', 'text-accent', 'my-10', 'text-[20px]', 'text-center'],
  GIT: ['px-1'],
  FINALLY_CONTAINER: [
    'max-w-screen-xl',
    'mx-auto',
    'mb-4',
    'p-4',
    'bg-orange',
    'border',
    'border-solid',
    'border-orange',
    'shadow-md',
    'rounded-lg',
  ],
  IMAGE: ['mx-auto'],
  RSSCHOOL_LINK: [
    'max-w-screen-xl',
    'mx-auto',
    'flex',
    'py-2',
    'px-8',
    'relative',
    'top-10',
    'sm:top-12',
    'justify-center',
    'w-fit',
    'bg-primary',
    'rounded-lg',
    'border-accent-hover',
    'border-6',
    'shadow-md',
    'hover:bg-white',
    'hover:border-accent',
  ],
  RSLOGO: ['w-[200px]', 'block'],
};
