export const CATALOG_STYLES = {
  PAGE_CONTAINER: ['container', 'max-w-[1440px]', 'mx-auto', 'px-4', 'py-10', 'flex-grow'],
  TITLE: ['text-3xl', 'text-center', 'font-semibold', 'text-black', 'mb-9'],
  CATALOG_CONTAINER: ['grid', 'grid-cols-1', 'xl:grid-cols-4', 'gap-8'],
  FILTERS_SECTION: [
    'xl:col-span-1',
    'bg-white',
    'border',
    'border-primary',
    'rounded-lg',
    'shadow-md',
    'p-4',
    'pb-10',
    'self-start',
  ],
  PRODUCT_LIST_SECTION: ['xl:col-span-3', 'flex', 'flex-col', 'gap-7', 'min-h-[500px]'],
  PRODUCT_LIST_CONTAINER: ['relative', 'flex-grow'],
  OVERLAY_PRODUCTS: [
    'absolute',
    'inset-0',
    'backdrop-blur-sm',
    'flex',
    'items-center',
    'justify-center',
    'z-10',
    'min-h-[200px]',
    'rounded-lg',
  ],
  OVERLAY_FILTERS: [
    'absolute',
    'inset-0',
    'backdrop-blur-sm',
    'flex',
    'items-center',
    'justify-center',
    'z-10',
    'min-h-[220px]',
    'rounded-lg',
  ],
  EMPTY_CATALOG_CONTAINER: [
    'flex',
    'flex-col',
    'items-center',
    'justify-center',
    'gap-6',
    'absolute',
    'inset-0',
    'backdrop-blur-sm',
    'flex',
    'items-center',
    'justify-center',
    'z-10',
    'min-h-[300px]',
  ],
  EMPTY_CATALOG_IMAGE: ['w-[250px]', 'h-[250px]'],
  EMPTY_CATALOG_TEXT: ['text-accent', 'text-xl', 'font-semibold'],
};
