export const CATALOG_STYLES = {
  PAGE_CONTAINER: ['px-4', 'py-10', 'flex-grow'],
  TITLE: ['text-3xl', 'text-center', 'font-semibold', 'text-black', 'mb-9'],
  CATALOG_CONTAINER: [
    'grid',
    'max-w-[1440px]',
    'mx-auto',
    'grid-cols-1',
    'xl:grid-cols-4',
    'gap-8',
  ],
  FILTERS_SECTION: [
    'xl:col-span-1',
    'bg-white',
    'border',
    'border-primary',
    'rounded-lg',
    'shadow-md',
    'p-4',
    'pb-10',
    'self-start',
    'relative',
  ],
  PRODUCT_LIST_SECTION: ['xl:col-span-3', 'flex', 'flex-col', 'gap-7', 'min-h-[500px]'],
  PRODUCT_LIST_CONTAINER: ['relative', 'flex-grow'],
  OVERLAY_PRODUCTS: [
    'absolute',
    'inset-0',
    'backdrop-blur-lg',
    'bg-white/80',
    'flex',
    'items-start',
    'justify-center',
    'z-10',
    'min-h-[200px]',
    'rounded-lg',
  ],
  OVERLAY_FILTERS: [
    'absolute',
    'inset-0',
    'backdrop-blur-lg',
    'bg-white/80',
    'flex',
    'items-start',
    'justify-center',
    'z-10',
    'min-h-[75px]',
    'xl:min-h-[150px]',
    'rounded-lg',
  ],
};
