export const PRODUCT_STYLES = {
  MAIN_CONTAINER: [
    'relative',
    'w-full',
    'px-4',
    'pt-5',
    'lg:pt-15',
    'pb-10',
    'flex',
    'flex-col',
    'text-dark',
    'leading-normal',
    'bg-gray-light',
    'flex-grow',
  ],
  CONTAINER: [
    'w-full',
    'max-w-[1440px]',
    'mx-auto',
    'flex',
    'flex-col',
    'lg:flex-row',
    'gap-8',
    'justify-between',
    'items-start',
    'mb-4',
  ],
  IMAGE: ['w-full', 'border', 'border-solid', 'border-primary', 'shadow-md', 'rounded-lg'],
  ASIDE: ['w-full', 'xl:w-2/3', 'flex', 'flex-col', 'gap-2'],
  TITLE_CONTAINER: ['flex', 'flex-col', 'gap-2', 'items-start', 'pb-4', 'rounded-lg', 'mr-5'],
  TITLE: ['text-2xl', 'md:text-3xl', 'pb-4', 'font-semibold', 'text-left'],
  DESCRIPTION: [],
  PARAMETER_NAME: ['font-semibold', 'pt-2', 'inline', 'mr-2'],
  PARAMETER_DESCRIPTION: ['inline', 'leading-[1.4]'],
  WRAPPING_BLOCK: ['xl:flex', 'xl:flex-row', 'xl:justify-between', 'xl:items-start', 'py-4'],
  PRICES_CONTAINER: [
    'relative',
    'p-4',
    'mx-auto',
    'flex',
    'flex-col',
    'md:w-lg',
    'bg-white',
    'border',
    'border-solid',
    'border-primary',
    'shadow-md',
    'rounded-lg',
  ],
  PRICE: ['text-accent', 'font-bold', 'text-4xl', 'text-center'],
  PRICE_OLD: ['text-2xl', 'place-self-start-center', 'line-through', 'place-self-center'],
  QUANTITY_BLOCK: ['flex', 'justify-center', 'items-center'],
  QUANTITY_INPUT: [
    'w-2',
    'h-2',
    'px-4',
    'py-4',
    'flex',
    'justify-center',
    'items-center',
    'text-xl',
    'font-bold',
    'border',
    'border-solid',
    'border-transparent',
    'text-black',
  ],
  QUANTITY_MESSAGE: ['font-semibold', 'pt-2', 'text-center', 'lg:text-left'],
  DELIVERY_CONTAINER: [
    'flex',
    'flex-col',
    'gap-1',
    'p-4',
    'mb-2',
    'bg-white',
    'border',
    'border-solid',
    'border-accent',
    'shadow-md',
    'rounded-lg',
  ],
  DELIVERY_ITEM: ['flex', 'items-center', 'gap-2'],
  DELIVERY_DESCRIPTION: ['text-sm', 'text-dark'],
  DETAILED_CONTAINER: [
    'w-full',
    'max-w-[1440px]',
    'mx-auto',
    'mt-2',
    'p-4',
    'bg-white',
    'border',
    'border-solid',
    'border-primary',
    'shadow-md',
    'rounded-lg',
  ],
  DETAILED_NAME: ['font-semibold', 'pt-2', 'text-lg'],
  SLIDER: [
    'w-full',
    'md:w-2/3',
    'xl:w-1/3',
    'm-auto',
    'lg:m-0',
    'max-h-screen',
    'p-3',
    'flex',
    'flex-col',
    'gap-3',
    'bg-white',
    'shadow-md',
    'rounded-lg',
    'sm:flex-row-reverse',
    'lg:flex-col',
    'items-start',
  ],
  SLIDER_IMAGE: ['max-w-full', 'max-h-full', 'object-contain', 'rounded-md'],
  SLIDER_BIG_IMAGE: [
    'w-full',
    'p-3',
    'aspect-square',
    'bg-white',
    'rounded-lg',
    'border',
    'border-gray',
    'hover:border-secondary-light',
    'cursor-pointer',
    'flex',
    'items-center',
    'justify-center',
  ],
  SLIDER_PREVIEW_CONTAINER: [
    'py-3',
    'flex',
    'items-end',
    'gap-2',
    'flex-wrap',
    'md:py-0',
    'sm:flex-col',
    'lg:py-3',
    'lg:flex-row',
  ],
  SLIDER_PREVIEW: [
    'w-[80px]',
    'aspect-square',
    'rounded-lg',
    'border',
    'border-gray',
    'cursor-pointer',
    'hover:border-secondary',
    'flex',
    'items-center',
    'justify-center',
    'bg-white',
  ],
  EMPTY_PRODUCT_CONTAINER: [
    'flex',
    'flex-col',
    'items-center',
    'justify-center',
    'gap-6',
    'absolute',
    'inset-0',
    'backdrop-blur-sm',
    'z-10',
    'px-4',
    'min-h-[300px]',
  ],
  EMPTY_PRODUCT_IMAGE: ['w-[250px]'],
  EMPTY_PRODUCT_TEXT: ['text-accent', 'text-xl', 'font-semibold', 'text-center'],
  ACTIVE_PREVIEW: ['border-secondary-light'],
};
