export const PRODUCT_STYLES = {
  MAIN_CONTAINER: [
    'w-full',
    'p-5',
    'flex',
    'flex-col',
    'text-base',
    'leading-normal',
    'bg-background',
    'flex-grow',
  ],
  CONTAINER: ['w-full', 'flex', 'gap-10', 'justify-between', 'items-start'],
  SLIDER: ['w-1/2'],
  IMAGE: ['w-full', 'rounded-sm'],
  ASIDE: ['w-1/2', 'flex', 'flex-col'],
  TITLE_CONTAINER: [
    'flex',
    'flex-col',
    'gap-2',
    'items-start',
    'px-2',
    'mb-4',
    'bg-white',
    'rounded-sm',
  ],
  TITLE: ['text-3xl', 'mb-4', 'font-semibold', 'text-left'],
  DESCRIPTION: [],
  PARAMETER_NAME: ['font-semibold', 'text-lg', 'mb-2'],
  PARAMETER_DESCRIPTION: ['mb-4'],
  PRICES_CONTAINER: [
    'grid',
    'grid-cols-2',
    'grid-rows-3',
    'w-full',
    'gap-2',
    'px-2',
    'my-2',
    'bg-white',
    'rounded-sm',
  ],
  PRICE: ['text-accent', 'font-bold', 'text-4xl'],
  PRICE_OLD: ['text-2xl', 'line-through'],
  QUANTITY_BLOCK: ['bg-red'],
  DELIVERY_CONTAINER: [
    'flex',
    'flex-col',
    'p-2',
    'mb-2',
    'bg-white',
    'rounded-sm',
    'border-2',
    'border-solid',
    'border-accent',
  ],
  DELIVERY_ITEM: ['flex', 'items-center', 'gap-2'],
  DELIVERY_DESCRIPTION: ['text-sm', 'text-dark'],
  DETAILED_CONTAINER: ['grid-col-span-2', 'p-2', 'bg-white', 'rounded-sm'],
};
