export enum INPUT_TYPE {
  TEXT = 'text',
  NUMBER = 'number',
  PASSWORD = 'password',
  DATE = 'date',
  CHECKBOX = 'checkbox',
  RADIO = 'radio',
  SEARCH = 'search',
  TEL = 'tel',
  EMAIL = 'email',
}

export enum BUTTON_TYPE {
  BUTTON = 'button',
  SUBMIT = 'submit',
  RESET = 'reset',
}

export const BUTTON_STYLE = {
  PRIMARY_PINK: [
    'bg-[#E7426A]',
    'text-white',
    'font-montserrat',
    'font-semibold',
    'text-[14px]',
    'w-[234px]',
    'px-3',
    'py-4',
    'rounded-[3px]',
    'cursor-pointer',
    'hover:bg-[#F45D82]',
    'disabled:bg-[#EDEDF0]',
    'disabled:cursor-not-allowed',
  ],
  SECONDARY_BLUE: [
    'bg-white',
    'text-[#4E9DD3]',
    'font-montserrat',
    'font-semibold',
    'text-[14px]',
    'w-[234px]',
    'px-3',
    'py-4',
    'border',
    'border-[#4E9DD3]',
    'rounded-[3px]',
    'cursor-pointer',
    'hover:bg-[#4E9DD3]',
    'hover:text-white',
    'disabled:bg-[#EDEDF0]',
    'disabled:border-[#EDEDF0]',
    'disabled:text-white',
    'disabled:cursor-not-allowed',
  ],
};
