export const FOOTER_STYLES = {
  FOOTER: ['bg-gray', 'py-15'],
  FOOTER_CONTAINER: [
    'max-w-[1440px]',
    'mx-auto',
    'px-3',
    'py-3',
    'grid',
    'grid-cols-1',
    'place-items-center',
    'md:grid-cols-3',
    'md:place-items-start',
    'gap-6',
    'md:px-4',
    'md:py-4',
  ],
  PROMO: ['flex', 'flex-col', 'items-center', 'gap-6', 'w-full', 'justify-between', 'col-span-1'],
  PROMO_ITEM: [
    'flex',
    'flex-row',
    'text-[14px]',
    'items-center',
    'justify-center',
    'md:justify-start',
    'text-center',
    'gap-2',
    'w-full',
  ],
  PROMO_ICON: ['w-6', 'h-6', 'md:w-8', 'md:h-8'],
};
