export const FOOTER_STYLES = {
  FOOTER: ['bg-gray', 'pt-15', 'border-t', 'border-primary'],
  FOOTER_CONTAINER: [
    'max-w-[1440px]',
    'mx-auto',
    'px-3',
    'py-3',
    'grid',
    'grid-cols-1',
    'gap-10',
    'place-items-center',
    'lg:grid-cols-3',
    'lg:place-items-start',
    'gap-6',
    'lg:px-4',
    'lg:py-4',
  ],
  PROMO: [
    'flex',
    'flex-col',
    'items-center',
    'lg:items-start',
    'gap-3',
    'lg:gap-6',
    'w-full',
    'justify-between',
    'col-span-1',
  ],
  TITLE: ['text-xl', 'font-bold', 'text-center', 'md:text-left', 'text-black'],
  PROMO_ITEM: [
    'flex',
    'flex-row',
    'text-[14px]',
    'items-center',
    'justify-center',
    'lg:justify-start',
    'text-center',
    'gap-2',
    'w-full',
    'text-black',
  ],
  PROMO_ICON: ['w-8', 'h-8'],
  MENU: ['flex', 'flex-col', 'items-center', 'lg:items-start', 'gap-6', 'w-full', 'col-span-1'],
  MENU_LIST: ['flex', 'flex-col', 'items-center', 'lg:items-start', 'gap-3', 'w-full'],
  MENU_ITEM: [
    'cursor-pointer',
    'text-[14px]',
    'text-center',
    'md:text-left',
    'text-secondary',
    'hover:text-accent-hover',
    'transition-all',
    'duration-300',
    'ease-in-out',
  ],
  TEAM: ['flex', 'flex-col', 'items-center', 'lg:items-start', 'gap-6', 'w-full', 'col-span-1'],
  TEAM_LIST: ['flex', 'flex-col', 'items-center', 'lg:items-start', 'gap-3', 'w-full'],
  TEAM_LINK: [
    'flex',
    'items-center',
    'gap-2',
    'text-[14px]',
    'text-secondary',
    'hover:text-accent-hover',
    'transition-all',
    'duration-300',
    'ease-in-out',
    'group',
  ],
  TEAM_ICON: [
    'w-6',
    'h-6',
    'fill-secondary',
    'group-hover:fill-accent-hover',
    'transition',
    'duration-300',
  ],
  COPYRIGHT: ['bg-primary', 'w-full', 'mt-10', 'py-6'],
  COPYRIGHT_CONTAINER: [
    'max-w-[1440px]',
    'mx-auto',
    'px-3',
    'flex',
    'flex-col',
    'items-center',
    'gap-3',
    'sm:gap-6',
    'lg:px-4',
  ],
  COPYRIGHT_LINK: [
    'flex',
    'items-center',
    'gap-2',
    'text-[14px]',
    'text-secondary',
    'hover:text-accent-hover',
    'transition-all',
    'duration-300',
    'ease-in-out',
  ],
  COPYRIGHT_ICON: ['w-5', 'h-5'],
};
