export const FOOTER_STYLES = {
  FOOTER: ['bg-gray', 'py-15'],
  FOOTER_CONTAINER: [
    'max-w-[1440px]',
    'mx-auto',
    'px-3',
    'py-3',
    'grid',
    'grid-cols-1',
    'gap-10',
    'place-items-center',
    'lg:grid-cols-3',
    'lg:place-items-start',
    'gap-6',
    'lg:px-4',
    'lg:py-4',
  ],
  PROMO: ['flex', 'flex-col', 'items-center', 'gap-6', 'w-full', 'justify-between', 'col-span-1'],
  TITLE: ['text-xl', 'font-bold', 'text-center', 'md:text-left'],
  PROMO_ITEM: [
    'flex',
    'flex-row',
    'text-[14px]',
    'items-center',
    'justify-center',
    'text-center',
    'gap-2',
    'w-full',
  ],
  PROMO_ICON: ['w-8', 'h-8'],
  MENU: ['flex', 'flex-col', 'items-center', 'gap-6', 'w-full', 'col-span-1'],
  MENU_LIST: ['flex', 'flex-col', 'items-center', 'gap-2', 'w-full'],
  MENU_ITEM: [
    'cursor-pointer',
    'text-center',
    'md:text-left',
    'hover:text-pink',
    'transition-all',
    'duration-300',
    'ease-in-out',
  ],
  MENU_LINK: ['text-[14px]'],
};
