import '../abstracts/colors.css';

export const BUTTON_STYLE = {
  PRIMARY_PINK: [
    'bg-[var(--button-primary-bg)]',
    'text-[var(--button-primary-text)]',
    'font-montserrat',
    'font-semibold',
    'text-[14px]',
    'w-[234px]',
    'px-3',
    'py-4',
    'rounded-[3px]',
    'cursor-pointer',
    'hover:bg-[var(--button-primary-bg-hover)]',
    'disabled:bg-[var(--button-disabled-bg)]',
    'disabled:cursor-not-allowed',
  ],
  SECONDARY_BLUE: [
    'bg-white',
    'text-[var(button-secondary-bg)]',
    'font-montserrat',
    'font-semibold',
    'text-[14px]',
    'w-[234px]',
    'px-3',
    'py-4',
    'border',
    'border-[var(--button-secondary-bg)]',
    'rounded-[3px]',
    'cursor-pointer',
    'hover:bg-[var(--button-secondary-bg)]',
    'hover:text-[var(--button-secondary-text-hover)]',
    'disabled:bg-[var(--button-disabled-bg)]',
    'disabled:border-[var(--button-disabled-bg)]',
    'disabled:text-white',
    'disabled:cursor-not-allowed',
  ],
};
