const STANDARD_BUTTON_STYLE = [
  'min-w-[234px]',
  'px-8',
  'py-4',
  'font-semibold',
  'text-[14px]',
  'border',
  'rounded-[3px]',
  'cursor-pointer',
  'transition-all',
  'duration-300',
  'ease-in-out',
  'disabled:bg-gray',
  'disabled:border-gray',
  'disabled:cursor-not-allowed',
];

export const DEFAULT_BUTTON_WITH_ICON = ['button', 'items-center', 'gap-2'];

export const BUTTON_ICON_CONTAINER = ['flex', 'items-center'];
export const BUTTON_ICON = ['w-5', 'h-5'];
export const BUTTON_TEXT = ['text-[14px]', 'font-semibold'];

export const CUSTOM_BUTTON_STYLE = {
  PRIMARY_PINK: [
    ...STANDARD_BUTTON_STYLE,
    'bg-accent',
    'text-white-permanent',
    'border-accent',
    'hover:bg-accent-hover',
    'hover:border-accent-hover',
    'active:bg-pink',
  ],
  SECONDARY_BLUE: [
    ...STANDARD_BUTTON_STYLE,
    'bg-transparent',
    'text-secondary',
    'border-secondary',
    'hover:bg-secondary-light',
    'hover:text-white',
  ],
  SECONDARY_PINK: [
    ...STANDARD_BUTTON_STYLE,
    'bg-white',
    'text-accent',
    'border-accent',
    'hover:bg-accent-hover',
    'hover:text-white-permanent',
  ],
  SECONDARY_BLUE_DARK: [
    ...STANDARD_BUTTON_STYLE,
    'bg-transparent',
    'text-white-permanent',
    'border-secondary',
    'hover:bg-secondary-light',
  ],
  SECONDARY_PINK_FILTER: [
    'min-w-[200px]',
    'px-6',
    'py-4',
    'font-semibold',
    'text-[14px]',
    'border',
    'rounded-[3px]',
    'cursor-pointer',
    'transition-all',
    'duration-300',
    'ease-in-out',
    'disabled:bg-gray',
    'disabled:border-gray',
    'disabled:cursor-not-allowed',
    'bg-white',
    'text-accent',
    'border-accent',
    'hover:bg-accent-hover',
    'hover:text-white-permanent',
    'mt-5',
  ],
  SHOW_MORE: ['text-accent', 'text-sm', 'cursor-pointer', 'hover:text-accent-hover', 'self-start'],
  PRICE_BUTTON: [
    ...STANDARD_BUTTON_STYLE,
    'bg-accent',
    'text-white-permanent',
    'border-accent',
    'hover:bg-accent-hover',
    'hover:border-accent-hover',
    'active:bg-pink',
    'lg:col-span-2',
    'w-[200px]',
    'place-self-center',
    'text-[14px]',
    'w-full',
  ],
  PRICE_QUANTITY: [
    'cursor-pointer',
    'w-8',
    'h-8',
    'flex',
    'justify-center',
    'items-center',
    'text-2xl',
    'font-bold',
    'bg-white',
    'border-2',
    'border-primary',
    'hover:bg-primary',
    'hover:text-black',
    'active:bg-primary',
    'rounded-sm',
    'text-black',
  ],
  CLEAR: [
    'hidden',
    'absolute',
    'right-10',
    'top-1/2',
    '-translate-y-1/2',
    'text-black',
    'hover:text-accent',
    'cursor-pointer',
    'text-lg',
    'font-bold',
  ],
  FILTER_TAG_DELETE: [
    'cursor-pointer',
    'mx-1',
    'p-1',
    'text-black',
    'hover:text-accent',
    'text-lg',
    'font-semibold',
  ],
  TOGGLE_FILTERS: [
    ...STANDARD_BUTTON_STYLE,
    'bg-transparent',
    'text-secondary',
    'border-secondary',
    'hover:bg-secondary-light',
    'hover:text-white',
    'xl:hidden',
  ],
  HIDDEN: ['hidden'],
  VISIBLE: ['block'],
  CLOSE: ['text-accent', 'font-bold', 'cursor-pointer', 'px-1', 'outline-none'],
  SEARCH_BUTTON: [
    'absolute',
    'right-2',
    'top-1/2',
    '-translate-y-1/2',
    'p-1',
    'rounded-lg',
    'hover:bg-orange-light',
    'focus:outline-none',
    'cursor-pointer',
  ],
  ICON_OUTLINE: [
    'cursor-pointer',
    'text-2xl',
    'block',
    'bg-accent',
    'w-[40px]',
    'h-[40px]',
    'rounded-md',
  ],
  SUBHEADER_ICON_OUTLINE: [
    'cursor-pointer',
    'flex',
    'items-center',
    'justify-center',
    'w-[30px]',
    'h-[30px]',
  ],
  ADDRESS_PRIMARY: [
    'flex',
    'p-2',
    'text-[14px]',
    'border',
    'rounded-[3px]',
    'cursor-pointer',
    'transition-all',
    'duration-300',
    'ease-in-out',
    'disabled:bg-gray',
    'disabled:border-gray',
    'disabled:cursor-not-allowed',
    'bg-white',
    'text-dark',
    'border-gray',
    'hover:bg-accent-hover',
    'hover:border-accent-hover',
  ],
  DELETE_CART_ITEM: [
    'flex-none',
    'absolute',
    'font-bold',
    'top-[5px]',
    'right-[5px]',
    'cursor-pointer',
    'p-1',
    'text-background',
    'hover:text-accent',
    'transition',
    'rounded-md',
    'hover:bg-orange',
  ],
  PAGINATOR_PINK: [
    'p-2',
    'text-[14px]',
    'border',
    'border-accent',
    'rounded-[3px]',
    'cursor-pointer',
    'transition-all',
    'duration-300',
    'ease-in-out',
    'disabled:bg-gray',
    'disabled:border-gray',
    'disabled:cursor-not-allowed',
    'bg-accent',
    'text-white',
    'hover:bg-accent-hover',
    'hover:border-accent-hover',
  ],
  ADD_TO_CART: [
    'min-w-[234px]',
    'px-8',
    'py-4',
    'font-semibold',
    'text-[14px]',
    'border',
    'rounded-[3px]',
    'cursor-pointer',
    'transition-all',
    'duration-300',
    'ease-in-out',
    'disabled:bg-red',
    'disabled:border-red',
    'disabled:cursor-not-allowed',
    'mx-2',
    'mt-2',
    'mb-4',
    'bg-accent',
    'text-white-permanent',
    'border-accent',
    'hover:bg-accent-hover',
    'hover:border-accent-hover',
    'active:bg-pink',
    'flex',
    'justify-center',
    'items-center',
    'gap-2',
  ],
  PROMO_CODE_SUBMIT: [
    'h-[52px]',
    'bg-accent',
    'rounded-[3px]',
    'cursor-pointer',
    'transition-all',
    'text-white-permanent',
    'hover:bg-accent-hover',
    'active:bg-pink',
    'font-bold',
    'text-[14px]',
  ],
  CLEAR_CART: [
    ...STANDARD_BUTTON_STYLE,
    'bg-accent',
    'text-white-permanent',
    'border-accent',
    'hover:bg-accent-hover',
    'hover:border-accent-hover',
    'active:bg-pink',
    'mb-3',
    'mt-7',
    'self-center',
    'transition-all',
  ],
  DISABLE: ['!cursor-not-allowed', '!bg-gray', '!border-gray', '!text-white'],
};
