export const HEADER_STYLES = {
  HEADER: [],
  HEADER_CONTAINER: [
    'max-w-[1440px]',
    'mx-auto',
    'px-3',
    'py-3',
    'flex',
    'items-center',
    'md:px-4',
    'md:py-4',
  ],
  LOGO: ['w-[80px]', 'sm:w-[110px]', 'md:w-[120px]', 'cursor-pointer'],
  MAIN_MENU: [
    'flex',
    'flex-1',
    'flex-col',
    'justify-start',
    'items-end',
    'ml-25',
    'gap-6',
    'md:gap-8',
    'sm:gap-4',
    'sm:flex-row',
    'sm:items-center',
  ],
  MENU_ITEM: [
    'cursor-pointer',
    'text-dark',
    'hover:text-accent',
    'uppercase',
    'transition-all',
    'duration-300',
    'ease-in-out',
    'text-[12px]',
    'md:text-[14px]',
  ],
};
