export const HEADER_STYLES = {
  HEADER: ['relative'],
  HEADER_CONTAINER: [
    'max-w-[1440px]',
    'mx-auto',
    'px-3',
    'py-3',
    'flex',
    'items-center',
    'md:px-4',
    'md:py-4',
  ],
  LOGO: ['w-[80px]', 'sm:w-[110px]', 'md:w-[120px]', 'cursor-pointer'],
  MAIN_MENU: [
    'flex',
    'flex-1',
    'justify-start',
    'items-end',
    'ml-7',
    'sm:ml-25',
    'gap-6',
    'md:gap-8',
    'sm:gap-4',
    'flex-row',
    'items-center',
  ],
  MENU_NAV: [
    'flex',
    'gap-10',
    'flex-wrap',
    'flex-col',
    'md:flex-row',
    'h-full',
    'md:h-auto',
    'w-full',
    'md:w-auto',
    'fixed',
    'md:relative',
    'top-[36px]',
    'md:top-0',
    'left-0',
    'z-5',
    'bg-white',
    'justify-center',
    'md:justify-start',
    'items-center',
  ],
  MENU_NAV_OPEN: [
    'flex',
    'gap-10',
    'flex-wrap',
    'flex-col',
    'md:flex-row',
    'h-full',
    'md:h-auto',
    'w-full',
    'md:w-auto',
    'fixed',
    'md:relative',
    'top-[36px]',
    'md:top-0',
    'left-0',
    'z-5',
    'bg-white',
    'justify-center',
    'md:justify-start',
    'items-center',
  ],
  MENU_NAV_CLOSED: [
    'flex',
    'gap-10',
    'flex-wrap',
    'flex-col',
    'md:flex-row',
    'h-full',
    'md:h-auto',
    'w-full',
    'md:w-auto',
    'fixed',
    'md:relative',
    'top-[36px]',
    'md:top-0',
    'left-full',
    'z-5',
    'bg-white',
    'justify-center',
    'md:justify-start',
    'items-center',
  ],
  MENU_ITEM: [
    'cursor-pointer',
    'text-black',
    'hover:text-accent',
    'uppercase',
    'transition-all',
    'duration-300',
    'ease-in-out',
    'text-3xl',
    'md:text-base',
    'font-semibold',
  ],
  BURGER_BUTTON: [
    'block',
    'md:hidden',
    'flex',
    'flex-col',
    'gap-3',
    'absolute',
    'right-[10px]',
    'z-10',
    'cursor-pointer',
    'p-2',
  ],
  BURGER_ICON_TOP: ['block', 'w-[25px]', 'h-[1px]', 'bg-accent', 'hover:bg-accent-hover'],
  BURGER_ICON_BOTTOM: ['block', 'w-[25px]', 'h-[1px]', 'bg-accent', 'hover:bg-accent-hover'],
};
