export const PROMO_HEADER_STYLES = {
  PROMO_HEADER: ['bg-pink', 'text-white-permanent', 'py-2', 'relative', 'z-10'],
  PROMO_HEADER_CONTAINER: [
    'container',
    'max-w-[1440px]',
    'mx-auto',
    'px-4',
    'flex',
    'justify-center',
    'items-center',
  ],
  PROMO_CODE: ['text-base', 'font-medium', 'text-center'],
  STARS_CONTAINER: [
    'hidden',
    'sm:block',
    'absolute',
    'inset-y-0',
    'w-[190px]',
    'bg-[url(@/assets/images/promo/promo-stars-gold.svg)]',
    'bg-contain',
    'bg-no-repeat',
  ],
  STARS_LEFT: ['left-4', 'bg-left'],
  STARS_RIGHT: ['right-4', 'bg-right'],
};
