export const SUBHEADER_STYLES = {
  SUBHEADER: ['bg-primary', 'py-2', 'text-[14px]', 'flex', 'justify-center'],
  SUBHEADER_CONTAINER: [
    'max-w-[1440px]',
    'flex',
    'justify-center',
    'lg:justify-between',
    'w-full',
    'px-3',
    'md:px-4',
  ],
  PROMO: ['hidden', 'lg:flex', 'flex-row', 'items-start', 'gap-4', 'lg:gap-8', 'xl:gap-12'],
  PROMO_ITEM: ['flex', 'items-center', 'gap-1.5', 'md:gap-2'],
  PROMO_ICON: ['w-4', 'h-4', 'md:w-5', 'md:h-5'],
  AUTHORIZATION_MENU: [
    'flex',
    'w-full',
    'max-w-[350px]',
    'lg:max-w-[300px]',
    'lg:min-w-[300px]',
    'flex-row',
    'flex-wrap',
    'justify-around',
    'lg:justify-end',
    'items-center',
    'lg:ml-10',
    'gap-5',
    'lg:gap-8',
  ],
  AUTHORIZATION_ITEM: [
    'cursor-pointer',
    'font-semibold',
    'text-accent',
    'hover:text-accent-hover',
    'transition-colors',
    'duration-300',
    'text-base',
    'lg:text-[14px]',
    'flex',
    'items-center',
    'gap-2',
  ],
  AUTHORIZATION_ITEM_ICON: ['w-6', 'h-6'],
  THEME_ICON: ['w-5', 'h-5'],
  THEME_TEXT: ['hidden'],
};
