export const SUBHEADER_STYLES = {
  SUBHEADER: [
    'bg-primary',
    'font-montserrat',
    'py-1',
    'text-[12px]',
    'flex',
    'justify-center',
    'sm:py-1.5',
    'md:py-2',
    'md:text-[14px]',
  ],
  SUBHEADER_CONTAINER: [
    'max-w-[1440px]',
    'flex',
    'justify-center',
    'md:justify-between',
    'w-full',
    'px-3',
    'md:px-4',
  ],
  PROMO: ['hidden', 'md:flex', 'flex-row', 'items-start', 'gap-4', 'lg:gap-8', 'xl:gap-15'],
  PROMO_ITEM: ['flex', 'items-center', 'gap-1.5', 'md:gap-2'],
  PROMO_ICON: ['w-4', 'h-4', 'md:w-5', 'md:h-5'],
  AUTHORIZATION_MENU: [
    'flex',
    'min-w-[205px]',
    'flex-row',
    'justify-end',
    'items-center',
    'gap-10',
    'ml-10',
    'sm:gap-6',
    'md:gap-8',
  ],
  AUTHORIZATION_ITEM: [
    'cursor-pointer',
    'font-semibold',
    'text-accent',
    'hover:text-accent-light',
    'transition-colors',
    'duration-300',
    'text-base',
    'md:text-[14px]',
  ],
};
