export const ABOUT_STYLE = {
  CONTAINER: [
    'w-full',
    'max-w-screen-xl',
    'grid',
    'grid-cols-2',
    'grid-rows-4',
    'gap-4',
    'mx-auto',
    'px-4',
    'py-10',
    'flex-grow',
  ],
  IMAGE_CONTAINER: ['relative', 'flex-1', 'mt-50', 'h-full', 'w-full'],
  OLGA_PHOTO: ['relative', 'top-10', 'left-8'],
  OLGA_HAT: ['relative', '-top-108', 'left-48', 'rotate-15'],
  OLGA_FRAME: ['relative'],
  KONSTANTIN_PHOTO: ['relative', 'top-10', 'left-8'],
  KONSTANTIN_HAT: ['relative', '-top-114', 'left-54', 'rotate-10'],
  KONSTANTIN_FRAME: ['relative'],
  DANIIL_PHOTO: ['relative', 'top-10', 'left-8'],
  DANIIL_HAT: ['relative', 'w-[190px]', '-top-95', 'left-28', '-rotate-1'],
  TEXT_CONTAINER: [],
  DESCRIPTION: [],
  ROLE: [],
  NAME: [],
};
