export const ABOUT_STYLE = {
  MAIN_CONTAINER: [
    'bg-gray-light',
    'bg-[url(@/assets/images/about/night-cafe.jpg)]',
    'bg-bottom',
    'bg-no-repeat',
    'bg-contain',
    // 'bg-size-[500px_auto]',
  ],
  TITLE: ['text-3xl', 'font-semibold', 'text-center', 'text-purple', 'my-6'],
  CONTAINER: [
    'w-full',
    'max-w-screen-xl',
    'flex',
    'flex-col',
    'grid-cols-2',
    'grid-rows-4',
    'gap-4',
    'mx-auto',
    'px-4',
    'py-10',
    'flex-grow',
  ],
  IMAGE_CONTAINER: ['relative', 'w-full'],
  PERSONAL_CONTAINER: ['flex'],
  ODD_CONTAINER: ['flex', 'flex-row-reverse'],
  OLGA_PHOTO: ['relative'],
  OLGA_HAT: ['relative', '-top-108', 'left-48', 'rotate-15'],
  KONSTANTIN_PHOTO: ['relative'],
  KONSTANTIN_HAT: ['relative', '-top-114', 'left-54', 'rotate-10'],
  DANIIL_PHOTO: ['relative'],
  DANIIL_HAT: ['relative', 'w-[190px]', '-top-95', 'left-28', '-rotate-1'],
  TEXT_CONTAINER: [
    'w-full',
    'p-4',
    'bg-white',
    'border',
    'border-solid',
    'border-primary',
    'shadow-md',
    'rounded-lg',
  ],
  NAME: ['font-bold', 'text-[18px]', 'my-4'],
  ROLE: ['text-purple', 'font-bold', 'text-[14px]', 'my-4'],
  DESCRIPTION: [],
};
