export const GUARANTEES_STYLES = {
  SECTION: ['w-full', 'py-10'],
  TITLE: ['text-3xl', 'font-semibold', 'text-center', 'mb-10', 'text-black'],
  LIST: ['grid', 'grid-cols-1', 'sm:grid-cols-2', 'xl:grid-cols-4', 'gap-8'],
  CARD: [
    'group',
    'border-primary',
    'border-1',
    'rounded-md',
    'shadow-md',
    'p-8',
    'flex',
    'flex-col',
    'items-center',
    'text-center',
    'hover:border-orange',
  ],
  IMAGE: [
    'mb-5',
    'rounded-md',
    'transition-transform',
    'duration-500',
    'group-hover:scale-105',
    'group-hover:drop-shadow-lg',
  ],
  CARD_TITLE: ['text-lg', 'font-semibold', 'mb-3', 'text-black'],
  CARD_DESCRIPTION: ['text-sm', 'text-black'],
};
