export const INTRO_STYLES = {
  SECTION: [
    'flex',
    'flex-col-reverse',
    'md:flex-row',
    'items-stretch',
    'justify-between',
    'md:gap-15',
    'mx-auto',
  ],
  IMAGE: ['w-full', 'md:w-1/2', 'h-auto', 'object-contain'],
  CONTENT: [
    'flex',
    'flex-col',
    'gap-6',
    'pt-5',
    'md:py-8',
    'md:py-20',
    'md:bg-[url(@/assets/images/promo/bg.png)]',
    'md:bg-no-repeat',
    'md:bg-left-top',
    'md:bg-right-bottom',
    'md:bg-contain',
    'xl:mt-20',
    'lg:mt-10',
  ],
  NAMECONTAINER: ['flex', 'flex-col', 'gap-2', 'items-center', 'mt-10', 'md:mt-0'],
  NAME: ['text-2xl', 'font-semibold'],
  SINCE: ['text-base', 'font-semibold'],
  TITLE: ['text-4xl', 'font-semibold', 'text-center', 'md:mt-5'],
  CATCH_PHRASE: ['text-lg', 'text-center'],
};
