export const PACKAGES_STYLES = {
  SECTION: [
    'w-full',
    'grid',
    'grid-cols-1',
    'sm:grid-cols-2',
    'lg:grid-cols-2',
    'xl:grid-cols-2',
    'gap-8',
    'pb-10',
  ],
  CARD: [
    'flex',
    'flex-col',
    'items-center',
    'justify-center',
    'rounded-md',
    'shadow-md',
    'py-10',
    'px-10',
    'lg:px-20',
  ],
  ICON: ['mb-4'],
  TITLE: ['text-xl', 'font-semibold', 'mb-2', 'text-center'],
  DESCRIPTION: ['text-base', 'text-center'],
};
